on: [push, pull_request]

name: Run README

jobs:
  test-data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Run tests on data on s3
        run: Rscript -e 'install.packages("devtools","aws.s3","usethis"))' -e 'b <- Sys.getenv("BUCKET")' \
                     -e 'aws.s3::s3load(bucket = b, object = "ufc_stats.rda")' \
                     -e 'usethis::use_data(ufc_stats, overwrite = TRUE)' -e 'devtools::test()'
        env: # Or as an environment variable
          ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.AWS_S3_BUCKET }}
