on:
  push:
    branches:
    - master

jobs:

  test-data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Run tests on data on s3
        run: Rscript -e 'install.packages(c("devtools","aws.s3","usethis"))' -e 'b <- Sys.getenv("BUCKET")' \
                     -e 'aws.s3::s3load(bucket = b, object = "ufc_stats.rda")' \
                     -e 'usethis::use_data(ufc_stats, overwrite = TRUE)' -e 'devtools::test()'
        env:
          ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.AWS_S3_BUCKET }}

  deploy:
    needs: test-data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mtoto/s3-sync-action@master
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
        DEST_DIR: 'data'

